app:
  storage:
    name: sql
    sql:
      dsn: "postgres://calendar:calendar@postgres:5432/calendar?sslmode=disable"
      maxIdleConns: 2
      maxOpenConns: 2
    memory:
logger:
  output: stderr
  level: debug
  devMode: true
server:
  http:
    addr: ":8080"
  grpc:
    addr: ":8081"
